#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold 2>/dev/null || true)
  DIM=$(tput dim 2>/dev/null || true)
  RESET=$(tput sgr0 2>/dev/null || true)
  BLUE=$(tput setaf 4 2>/dev/null || true)
  GREEN=$(tput setaf 2 2>/dev/null || true)
  YELLOW=$(tput setaf 3 2>/dev/null || true)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# Bind repository-scoped writes to the repository containing this wizard, not
# to whichever directory the caller happened to launch it from. Authors may set
# WIZARD_ROOT before launch when the script intentionally lives elsewhere.
_WIZARD_SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
_WIZARD_ROOT_CANDIDATE="${WIZARD_ROOT:-$_WIZARD_SCRIPT_DIR}"
if ! WIZARD_ROOT=$(git -C "$_WIZARD_ROOT_CANDIDATE" rev-parse --show-toplevel 2>/dev/null); then
  WIZARD_ROOT=""
fi
readonly WIZARD_ROOT

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then
    tput clear 2>/dev/null || printf '\033[2J\033[3J\033[H'
  else
    printf '\033[2J\033[3J\033[H'
  fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local lines line
  lines=$(grep -E "^${1}=" "$ENV_FILE") || return 1
  line=$(printf '%s\n' "$lines" | tail -n1)
  local value="${line#*=}"
  if [[ "$value" == \"*\" ]]; then
    value=${value:1:${#value}-2}
    value=${value//\\\`/\`}
    value=${value//\\\$/\$}
    value=${value//\\\"/\"}
    value=${value//\\\\/\\}
  fi
  printf '%s' "$value"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current="" input="" has_current=false
  if current=$(_existing "$key") && [[ -n "$current" ]]; then
    has_current=true
  fi
  while :; do
    if [[ "$has_current" == true ]]; then
      printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    if ! IFS= read -r input; then
      warn "no input available — run this wizard in an interactive terminal"
      return 1
    fi
    if [[ -z "$input" && "$has_current" == true ]]; then
      input="$current"
      break
    fi
    [[ -n "$input" ]] && break
    warn "a value is required"
  done
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current="" input="" has_current=false
  if [[ ! -t 0 ]]; then
    warn "refusing to read a secret from non-terminal input"
    return 1
  fi
  if current=$(_existing "$key") && [[ -n "$current" ]]; then
    has_current=true
  fi
  while :; do
    if [[ "$has_current" == true ]]; then
      printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    if ! IFS= read -rs input; then
      printf '\n'
      warn "secret input ended before a value was captured"
      return 1
    fi
    printf '\n'
    if [[ -z "$input" && "$has_current" == true ]]; then
      input="$current"
      break
    fi
    [[ -n "$input" ]] && break
    warn "a value is required"
  done
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp encoded
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1 \
    && ! git check-ignore -q -- "$ENV_FILE"; then
    warn "refusing to write $ENV_FILE — add it to .gitignore first"
    SKIPPED+=("$key in $ENV_FILE ($ENV_FILE is not git-ignored)")
    return 1
  fi
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    warn "refusing to write multiline value for $key to $ENV_FILE"
    SKIPPED+=("$key in $ENV_FILE (value contained a newline)")
    return 1
  fi
  encoded=${value//\\/\\\\}
  encoded=${encoded//\"/\\\"}
  encoded=${encoded//\$/\\$}
  encoded=${encoded//\`/\\\`}
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s="%s"\n' "$key" "$encoded" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# _github_repo — resolve [HOST/]OWNER/REPO from the validated wizard root.
_github_repo() {
  [[ -n "$WIZARD_ROOT" ]] || return 1
  (
    unset GH_REPO
    cd -- "$WIZARD_ROOT"
    # shellcheck disable=SC2016 # jq expands $host, not the shell.
    gh repo view --json nameWithOwner,url --jq \
      '(.url | sub("^https?://"; "") | split("/")[0]) as $host | if $host == "github.com" then .nameWithOwner else "\($host)/\(.nameWithOwner)" end'
  )
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Records and
# returns failure if gh is unavailable, unauthenticated, the repository cannot
# be resolved from WIZARD_ROOT, or the write fails.
set_secret() {
  local name="$1" value="$2" repo
  if [[ -z "$value" ]]; then
    SKIPPED+=("GitHub secret $name (captured value was empty)")
    warn "refusing to set empty GitHub secret $name"
    return 1
  fi
  if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
    SKIPPED+=("GitHub secret $name (authenticate gh, then set it manually)")
    warn "couldn't set GitHub secret $name — gh is unavailable or unauthenticated"
    return 1
  fi
  if ! repo=$(_github_repo); then
    SKIPPED+=("GitHub secret $name (couldn't resolve the wizard repository)")
    warn "couldn't set GitHub secret $name — wizard repository is unavailable"
    return 1
  fi
  if ! printf '%s' "$value" | gh secret set "$name" --repo "$repo" >/dev/null 2>&1; then
    SKIPPED+=("GitHub secret $name (gh write failed)")
    warn "couldn't set GitHub secret $name — gh write failed"
    return 1
  fi
  WRITTEN_SECRET+=("$name")
  printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2" repo
  if [[ -z "$value" ]]; then
    SKIPPED+=("GitHub variable $name (captured value was empty)")
    warn "refusing to set empty GitHub variable $name"
    return 1
  fi
  if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
    SKIPPED+=("GitHub variable $name (authenticate gh, then set it manually)")
    warn "couldn't set GitHub variable $name — gh is unavailable or unauthenticated"
    return 1
  fi
  if ! repo=$(_github_repo); then
    SKIPPED+=("GitHub variable $name (couldn't resolve the wizard repository)")
    warn "couldn't set GitHub variable $name — wizard repository is unavailable"
    return 1
  fi
  if ! gh variable set "$name" --body "$value" --repo "$repo" >/dev/null 2>&1; then
    SKIPPED+=("GitHub variable $name (gh write failed)")
    warn "couldn't set GitHub variable $name — gh write failed"
    return 1
  fi
  printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  local incomplete=${#SKIPPED[@]}
  if (( incomplete )); then
    printf '\n%s%s  ! Setup incomplete%s\n' "$BOLD" "$YELLOW" "$RESET"
  else
    printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  fi
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( incomplete )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
  (( incomplete == 0 ))
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1
TOTAL_MINUTES=5

banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe — API keys" 5
say "We'll grab your Stripe test keys and store them for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the API keys page, copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
# Verify this name matches a corresponding secrets.* reference in CI.
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"   # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

finish
